import { useEffect, useRef, useState, type ReactNode } from 'react'
import { Database, RotateCcw } from 'lucide-react'
import { Button, Select, Skeleton, Switch } from '@/components/ui'
import { ControlEditor } from '@/components/settings/ControlEditor'
import { GamepadInput } from '@/input/gamepad'
import { APP_COMMANDS, GAME_ACTIONS, type InputBinding } from '@/input/inputTypes'
import { DEFAULT_GAMEPAD_MAPPING, DEFAULT_KEYBOARD_MAPPING } from '@/input/mappings'
import { DEFAULT_APP_SETTINGS, settingsService } from '@/services/settingsService'
import { getStorageEstimate, requestPersistentStorage, type StorageEstimate } from '@/services/storageEstimateService'
import type { AppSettings } from '@/types/settings'
import { formatBytes } from '@/utils/formatBytes'
import styles from './SettingsPage.module.css'

const LABELS: Record<InputBinding, string> = { UP: 'Up', DOWN: 'Down', LEFT: 'Left', RIGHT: 'Right', A: 'A', B: 'B', L: 'L', R: 'R', START: 'Start', SELECT: 'Select', QUICK_SAVE: 'Quick Save', QUICK_LOAD: 'Quick Load', FAST_FORWARD: 'Fast Forward', PAUSE: 'Pause', FULLSCREEN: 'Fullscreen', MENU: 'Menu' }

export function SettingsPage() {
  const [settings, setSettings] = useState<AppSettings>(); const [listening, setListening] = useState<InputBinding>(); const [controller, setController] = useState<string>(); const [notice, setNotice] = useState(''); const [storage, setStorage] = useState<StorageEstimate>(); const [editingControls, setEditingControls] = useState(false)
  const latestSettings = useRef<AppSettings | undefined>(undefined); const saveRevision = useRef(0)
  useEffect(() => { void settingsService.getAppSettings().then((value) => { latestSettings.current = value; setSettings(value) }); void getStorageEstimate().then(setStorage) }, [])
  useEffect(() => { if (!settings) return; const gamepad = new GamepadInput(settings.gamepad, () => undefined, setController); gamepad.start(); return () => gamepad.stop() }, [settings])
  async function persist(update: (current: AppSettings) => AppSettings, message = 'Settings saved.') {
    const current = latestSettings.current
    if (!current) return
    const next = update(current); const revision = ++saveRevision.current
    latestSettings.current = next; setSettings(next)
    try {
      const saved = await settingsService.saveAppSettings(next)
      if (revision === saveRevision.current) { latestSettings.current = saved; setSettings(saved); setNotice(message) }
    } catch { if (revision === saveRevision.current) setNotice('Settings could not be saved. Try again.') }
  }
  function mapKey(action: InputBinding, code: string) { if (!settings) return; setListening(undefined); void persist((current) => { const keyboard = { ...current.keyboard }; const duplicate = (Object.entries(keyboard) as [InputBinding, string][]).find(([other, mapped]) => other !== action && mapped === code); if (duplicate) keyboard[duplicate[0]] = keyboard[action]; keyboard[action] = code; return { ...current, keyboard } }) }
  async function requestStorage() { const granted = await requestPersistentStorage(true); setStorage(await getStorageEstimate()); setNotice(granted ? 'Persistent storage enabled.' : 'The browser did not grant persistent storage.') }
  if (!settings) return <SettingsSkeleton/>
  const keyboardActions = [...GAME_ACTIONS, ...APP_COMMANDS]
  return <main className={styles.page}><header className={styles.intro}><div><p className="code">Preferences</p><h1 className="display-large">Settings</h1><p>All settings are validated and stored only on this device.</p></div><Button variant="ghost" onClick={() => void persist(() => DEFAULT_APP_SETTINGS, 'All settings reset to defaults.')}><RotateCcw size={15}/>Reset all</Button></header>
    <Section title="Appearance"><SettingRow title="Color theme" description="Follow your device or choose a permanent light or dark appearance."><Select label="Color theme" labelHidden value={settings.appearance.theme} onChange={(event) => { const theme = event.target.value as AppSettings['appearance']['theme']; void persist((current) => ({ ...current, appearance: { theme } })) }}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></Select></SettingRow></Section>
    <Section title="General"><SettingRow title="Launch directly into last game" description="Open your most recently played game when PocketArc starts."><Switch label="Launch last game" checked={settings.general.launchLastGame} onChange={(value) => void persist((current) => ({ ...current, general: { ...current.general, launchLastGame: value } }))}/></SettingRow><SettingRow title="Confirm before game restart" description="Warn when restarting could discard progress."><Switch label="Confirm restart" checked={settings.general.confirmRestart} onChange={(value) => void persist((current) => ({ ...current, general: { ...current.general, confirmRestart: value } }))}/></SettingRow><SettingRow title="Keep screen awake while playing" description="Uses Screen Wake Lock where the browser supports it."><Switch label="Keep screen awake" checked={settings.general.keepAwake} onChange={(value) => void persist((current) => ({ ...current, general: { ...current.general, keepAwake: value } }))}/></SettingRow></Section>
    <Section title="Display"><SettingRow title="Integer scaling" description="Prefer whole-number scaling where the viewport permits it."><Switch label="Integer scaling" checked={settings.display.integerScaling} onChange={(value) => void persist((current) => ({ ...current, display: { ...current.display, integerScaling: value } }))}/></SettingRow><SettingRow title="Smooth filtering" description="Smooth scaled pixels instead of preserving hard edges."><Switch label="Smooth filtering" checked={settings.display.smoothFiltering} onChange={(value) => void persist((current) => ({ ...current, display: { ...current.display, smoothFiltering: value } }))}/></SettingRow><SettingRow title="Screen fit" description="Control how the 3:2 game image uses its available area."><Select label="Screen fit" labelHidden value={settings.display.screenFit} onChange={(event) => { const screenFit = event.target.value as AppSettings['display']['screenFit']; void persist((current) => ({ ...current, display: { ...current.display, screenFit } })) }}><option value="contain">Contain</option><option value="fill">Fill</option><option value="pixel-perfect">Pixel-perfect</option></Select></SettingRow><SettingRow title="Display filter" description="Use only filters supported by the bundled EmulatorJS runtime."><Select label="Display filter" labelHidden value={settings.display.filter} onChange={(event) => { const filter = event.target.value as AppSettings['display']['filter']; void persist((current) => ({ ...current, display: { ...current.display, filter } })) }}><option value="original">Original</option><option value="sharp">Sharp Pixels</option><option value="smooth">Smooth</option></Select></SettingRow><SettingRow title="Fullscreen behavior" description="Choose whether fullscreen includes PocketArc controls."><Select label="Fullscreen behavior" labelHidden value={settings.display.fullscreenBehavior} onChange={(event) => { const fullscreenBehavior = event.target.value as AppSettings['display']['fullscreenBehavior']; void persist((current) => ({ ...current, display: { ...current.display, fullscreenBehavior } })) }}><option value="app">Game and controls</option><option value="screen">Game screen only</option></Select></SettingRow></Section>
    <Section title="Touch controls" action={<Button onClick={() => setEditingControls((open) => !open)}>{editingControls ? 'Close editor' : 'Customize controls'}</Button>}><SettingRow title="Show controls" description="Show the on-screen controller on touch devices."><Switch label="Show touch controls" checked={settings.touch.showControls} onChange={(value) => void persist((current) => ({ ...current, touch: { ...current.touch, showControls: value } }))}/></SettingRow><Range label="Opacity" min={.3} max={1} step={.05} value={settings.touch.opacity} output={`${Math.round(settings.touch.opacity * 100)}%`} onChange={(value) => void persist((current) => ({ ...current, touch: { ...current.touch, opacity: value } }))}/><Range label="Size" min={.75} max={1.25} step={.05} value={settings.touch.size} output={`${Math.round(settings.touch.size * 100)}%`} onChange={(value) => void persist((current) => ({ ...current, touch: { ...current.touch, size: value } }))}/><SettingRow title="Haptic feedback" description="Vibrate briefly where supported."><Switch label="Haptic feedback" checked={settings.touch.haptics} onChange={(value) => void persist((current) => ({ ...current, touch: { ...current.touch, haptics: value } }))}/></SettingRow>{editingControls && <ControlEditor value={settings.touch} onCancel={() => setEditingControls(false)} onSave={async (touch) => { await persist((current) => ({ ...current, touch }), 'Touch layout saved.'); setEditingControls(false) }}/>}</Section>
    <Section title="Keyboard" action={<Button variant="ghost" onClick={() => void persist((current) => ({ ...current, keyboard: { ...DEFAULT_KEYBOARD_MAPPING } }), 'Keyboard mapping reset.')}><RotateCcw size={15}/>Reset defaults</Button>}><div className={styles.mappingGrid}>{keyboardActions.map((action) => <div className={styles.mapping} key={action}><span>{LABELS[action]}</span><button type="button" className={listening === action ? styles.captureActive : styles.capture} onClick={() => setListening(action)} onKeyDown={(event) => { if (listening === action) { event.preventDefault(); mapKey(action, event.code) } }}>{listening === action ? 'Press a key…' : formatCode(settings.keyboard[action])}</button></div>)}</div></Section>
    <Section title="Gamepad" description={controller ? `Connected: ${controller}` : 'No standard controller detected.'} action={<Button variant="ghost" onClick={() => void persist((current) => ({ ...current, gamepad: { ...DEFAULT_GAMEPAD_MAPPING } }), 'Gamepad mapping reset.')}><RotateCcw size={15}/>Reset mapping</Button>}><div className={styles.mappingGrid}>{GAME_ACTIONS.map((action) => <Select key={action} label={LABELS[action]} value={settings.gamepad[action]} onChange={(event) => { const button = Number(event.target.value); void persist((current) => ({ ...current, gamepad: { ...current.gamepad, [action]: button } })) }}>{Array.from({ length: 16 }, (_, index) => <option key={index} value={index}>Button {index}</option>)}</Select>)}</div></Section>
    <Section title="Audio"><Range label="Master volume" min={0} max={1} step={.05} value={settings.audio.masterVolume} output={`${Math.round(settings.audio.masterVolume * 100)}%`} onChange={(value) => void persist((current) => ({ ...current, audio: { ...current.audio, masterVolume: value } }))}/><SettingRow title="Mute" description="Start games with all emulator audio muted."><Switch label="Mute audio" checked={settings.audio.muted} onChange={(value) => void persist((current) => ({ ...current, audio: { ...current.audio, muted: value } }))}/></SettingRow></Section>
    <Section title="Storage"><div className={styles.storage}><Database size={18}/><div><strong>{storage?.supported ? `${formatBytes(storage.usage)} used of ${formatBytes(storage.quota)}` : 'Storage estimate unavailable'}</strong><span>{storage?.persistent ? 'Persistent storage is enabled.' : 'Standard browser storage is in use.'}</span></div><Button disabled={!storage?.supported || storage?.persistent} onClick={() => void requestStorage()}>{storage?.persistent ? 'Persistent' : 'Request persistent storage'}</Button></div></Section>
    <Section title="About" mobileHidden><dl className={styles.about}><div><dt>App version</dt><dd>0.1.0</dd></div><div><dt>EmulatorJS</dt><dd>4.2.3</dd></div><div><dt>Core</dt><dd>mGBA</dd></div></dl><p className={styles.privacy}>PocketArc has no accounts, analytics, ROM uploads, or cloud sync. Imported games, cover artwork, saves, screenshots, and settings remain in this browser profile.</p><div className={styles.licenseLinks}><a href="/emulatorjs/licenses/EmulatorJS-GPL-3.0.txt" target="_blank" rel="noreferrer">EmulatorJS license</a><a href="/emulatorjs/licenses/mGBA-MPL-2.0.txt" target="_blank" rel="noreferrer">mGBA license</a></div></Section>
    {notice && <p className={styles.notice} role="status">{notice}</p>}
  </main>
}

function Section({ action, children, description, mobileHidden = false, title }: { action?: ReactNode; children: ReactNode; description?: string; mobileHidden?: boolean; title: string }) { return <section className={`${styles.section} ${mobileHidden ? styles.mobileHidden : ''}`}><header className={styles.sectionHeader}><div><h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</header>{children}</section> }
function SettingRow({ children, description, title }: { children: ReactNode; description: string; title: string }) { return <div className={styles.settingRow}><div><strong>{title}</strong><span>{description}</span></div>{children}</div> }
function Range({ label, max, min, onChange, output, step, value }: { label: string; min: number; max: number; step: number; value: number; output: string; onChange: (value: number) => void }) { return <label className={styles.range}><span>{label}</span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))}/><output>{output}</output></label> }
function SettingsSkeleton() { return <main className={styles.page} aria-busy="true" aria-label="Loading settings"><Skeleton width={280} height={48}/>{Array.from({ length: 5 }, (_, index) => <Skeleton key={index} height={180}/>)}</main> }
function formatCode(code: string) { return code.replace(/^Key/, '').replace(/^Digit/, '').replace('Arrow', 'Arrow ') }
