import { useState, type ReactNode } from 'react'
import { AudioLines, Camera, Expand, Gamepad2, Gauge, Library, ListChecks, Monitor, Pause, Play, RotateCcw, Save, Upload } from 'lucide-react'
import { Button, Dialog, Sheet } from '@/components/ui'
import { KeyboardLegend } from '@/components/emulator/KeyboardLegend'
import type { KeyboardMapping } from '@/input/inputTypes'
import styles from './EmulatorShell.module.css'

type Props = { open: boolean; paused: boolean; fastForward: 1 | 2 | 4; volume: number; keyboard: KeyboardMapping; confirmRestart: boolean; onClose: () => void; onResume: () => void; onQuickSave: () => void; onQuickLoad: () => void; onSaveStates: () => void; onFastForward: (ratio: 1 | 2 | 4) => void; onScreenshot: () => void; onCheats: () => void; onControls: () => void; onFullscreen: () => void; onVolume: (value: number) => void; onRestart: () => void; onExit: () => void }

export function QuickMenu(props: Props) {
  const [restartOpen, setRestartOpen] = useState(false)
  const action = (callback: () => void) => () => { callback(); props.onClose() }
  return <><Sheet open={props.open} side="left" onClose={props.onClose} title="Play menu" description="Your game, saves, and session controls"><div className={styles.menuList}>
    <MenuButton className={styles.sessionAction} icon={props.paused ? Play : Pause} label={props.paused ? 'Resume game' : 'Pause game'} detail={props.paused ? 'Return to your session' : 'Gameplay keeps its current state'} onClick={action(props.onResume)}/>
    <MenuGroup title="Save and restore"><div className={styles.menuGrid}><MenuButton icon={Save} label="Quick Save" detail="Capture now" onClick={action(props.onQuickSave)}/><MenuButton icon={Upload} label="Quick Load" detail="Restore quick slot" onClick={action(props.onQuickLoad)}/></div><MenuButton icon={Save} label="Save States" detail="Manage Auto and Slots 1–3" onClick={action(props.onSaveStates)}/></MenuGroup>
    <MenuGroup title="Game tools"><div className={styles.menuGrid}><MenuButton icon={Camera} label="Screenshot" detail="Save locally" onClick={action(props.onScreenshot)}/><MenuButton icon={ListChecks} label="Cheats" detail="Per-game codes" onClick={action(props.onCheats)}/><MenuButton icon={Gamepad2} label="Controls" detail="Mappings and touch" onClick={action(props.onControls)}/><KeyboardLegend mapping={props.keyboard}/></div></MenuGroup>
    <MenuGroup title="Experience"><label className={styles.menuControl}><span className={styles.menuControlIcon}><Gauge size={17}/></span><span className={styles.menuControlCopy}><strong>Speed</strong><small>Fast-forward multiplier</small></span><select aria-label="Fast-forward speed" value={props.fastForward} onChange={(event) => props.onFastForward(Number(event.target.value) as 1 | 2 | 4)}><option value="1">1x</option><option value="2">2x</option><option value="4">4x</option></select></label><label className={styles.menuControl}><span className={styles.menuControlIcon}><AudioLines size={17}/></span><span className={styles.menuControlCopy}><strong>Audio</strong><small>{Math.round(props.volume * 100)}%</small></span><input aria-label="Quick menu volume" type="range" min="0" max="1" step="0.05" value={props.volume} onChange={(event) => props.onVolume(Number(event.target.value))}/></label><MenuButton icon={Expand} label="Display / Fullscreen" detail="Enter immersive play" onClick={action(props.onFullscreen)}/></MenuGroup>
    <MenuGroup title="Session"><MenuButton icon={RotateCcw} label="Restart Game" detail="Restart from the beginning" onClick={() => { if (props.confirmRestart) setRestartOpen(true); else { props.onClose(); props.onRestart() } }}/><MenuButton className={styles.exitAction} icon={Library} label="Exit to Library" detail="Save and close this session" onClick={props.onExit}/></MenuGroup>
  </div></Sheet><Dialog open={restartOpen} onClose={() => setRestartOpen(false)} title="Restart game?" description="Progress since your last in-game save or save state may be lost." footer={<><Button variant="ghost" onClick={() => setRestartOpen(false)}>Cancel</Button><Button variant="primary" onClick={() => { setRestartOpen(false); props.onClose(); props.onRestart() }}>Restart Game</Button></>}><p>Use Quick Save first if you want to preserve the current moment.</p></Dialog></>
}

function MenuGroup({ children, title }: { children: ReactNode; title: string }) { return <section className={styles.menuGroup}><h3>{title}</h3><div className={styles.menuGroupBody}>{children}</div></section> }

function MenuButton({ className = '', detail, icon: Icon, label, onClick }: { className?: string; detail?: string; icon: typeof Monitor; label: string; onClick: () => void }) { return <button type="button" className={`${styles.menuButton} ${className}`} aria-label={label} onClick={onClick}><span className={styles.menuButtonIcon} aria-hidden="true"><Icon size={17}/></span><span className={styles.menuButtonCopy}><strong>{label}</strong>{detail && <small aria-hidden="true">{detail}</small>}</span></button> }
